### ISSUE TITLE
Учет ФИО и даты рождения

### ISSUE THREAD

**Issue by JAkutenshi** [SammyVimes/IDP-Strikes-back#10]
* Добавить в класс Plan через QString поля 
   - ФИО
   - Дату рождения
* Сериализовать их
* Для имен файлов использовать соглашение: ddmmyyyyHHMMSS_Name_BDay.xml , где:
   - ddmmyyyyHHMMSS - дата создания файла (день, месяц, год, час, минута, секунда)
   - Name - ФИО пользователя, пробелы заменить на нижнее подчеркивание "_"
   - BDay - строка формата ddmmyyyy , убрав точки в изначальной строке (надо ли их там хранить?).

**Comment by SammyVimes** [comment]
fixed in https://github.com/SammyVimes/IDP-Strikes-back/commit/e8396c05e10fe542bcbf345937821511e425e8ab
