### ISSUE TITLE
Добавление статус-бара в окно формы

### ISSUE THREAD

**Issue by JAkutenshi** [SammyVimes/IDP-Strikes-back#11]
Требуется для отображения там подсказок при наведении на элементы формы:
* На ФИО - "Фамилия Имя Отчество через пробел
* На поле даты рождения - "Дата рождения в формате <День>.<Месяц>.<Год> (через точку)
* На поле запрещенной еды - "Перечислите, разделяя запятыми, продукты, запрещенные к употреблению"
* На список лекарств - "Доступные лекарства"
* На кнопку добавить после списка лекарств - "Добавить новое лекарство"
* На список еды - "Доступные блюда"
* На кнопку добавить после списка еды - "Добавить новое блюдо"
* На кнопку Добавить в конце формы - "Создать и открыть новый план"

**Comment by LeoSko** [comment]
@JAkutenshi посмотри то ли я добавил - при наведении мыши на поля появляется подсказка. В статус баре снизу отображается статус готовности работы.
