### ISSUE TITLE
Добавление списка принимаемых веществ (еда + лекарства) и информации по каждому элементу

### ISSUE THREAD

**Issue by JAkutenshi** [SammyVimes/IDP-Strikes-back#5]
Требуется добавить на окно просмотра графа горизонтальный лэйаут:
слева панель с просмотром графа, справа - вертикальный лэйаут.
вертикальный лэйаут содержит в себе сверху упорядоченный по порядку приема вещества для конкретного приема пищи, а внизу - информацию по каждому элементу.

**Comment by LeoSko** [comment]
@SammyVimes сделано ведь, да?

**Comment by SammyVimes** [comment]
Да)
